[colors]
background = '#0f17228e'
black = '#0f1722'
blue = '#4B5466'
cursor = '#c3c5c7'
cyan = '#5A5761'
foreground = '#c3c5c7'
green = '#A0081A'
magenta = '#B43644'
red = '#976868'
tabs = '#c3c5c7'
tabs-active = '#A1769F'
white = '#c3c5c7'
yellow = '#c3c5c7'
dim-black = '#0f17228e'
dim-blue = '#4B54668e'
dim-cyan = '#5A57618e'
dim-foreground = '#c3c5c78e'
dim-green = '#A0081A8e'
dim-magenta = '#B436448e'
dim-red = '#9768688e'
dim-white = '#A1769F8e'
dim-yellow = '#c3c5c78e'
light-black = '#4B5466'
light-blue = '#5A5761'
light-cyan = '#A0081A'
light-foreground = '#B43644'
light-green = '#976868'
light-magenta = '#A1769F'
light-red = '#c3c5c7'
light-white = '#4B5466'
light-yellow = '#5A5761'
