# Shell variables
# Generated by 'wal'
wallpaper="/home/furro/Pictures/wallpapers/wallpaper.jpg"

# Special
background='#0f1722'
foreground='#c3c5c7'
cursor='#c3c5c7'

# Colors
color0='#0f1722'
color1='#4B5466'
color2='#5A5761'
color3='#A0081A'
color4='#B43644'
color5='#976868'
color6='#A1769F'
color7='#c3c5c7'
color8='#5e6773'
color9='#4B5466'
color10='#5A5761'
color11='#A0081A'
color12='#B43644'
color13='#976868'
color14='#A1769F'
color15='#c3c5c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
