--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/furro/Pictures/wallpapers/wallpaper.jpg"

-- Special
background="#0f1722"
foreground="#c3c5c7"
cursor="#c3c5c7"

-- Colors
color0="#0f1722"
color1="#4B5466"
color2="#5A5761"
color3="#A0081A"
color4="#B43644"
color5="#976868"
color6="#A1769F"
color7="#c3c5c7"
color8="#5e6773"
color9="#4B5466"
color10="#5A5761"
color11="#A0081A"
color12="#B43644"
color13="#976868"
color14="#A1769F"
color15="#c3c5c7"
