foreground         #c3c5c7
background         #0f1722
background_opacity 1.0
cursor             #c3c5c7

active_tab_foreground     #0f1722
active_tab_background     #c3c5c7
inactive_tab_foreground   #c3c5c7
inactive_tab_background   #0f1722

active_border_color   #c3c5c7
inactive_border_color #0f1722
bell_border_color     #4B5466

color0       #0f1722
color8       #5e6773
color1       #4B5466
color9       #4B5466
color2       #5A5761
color10      #5A5761
color3       #A0081A
color11      #A0081A
color4       #B43644
color12      #B43644
color5       #976868
color13      #976868
color6       #A1769F
color14      #A1769F
color7       #c3c5c7
color15      #c3c5c7
