# pywal theme for ghostty

background = 0f1722
foreground = c3c5c7
cursor-color = c3c5c7
selection-background = c3c5c7
selection-foreground = 0f1722

palette = 0=#0f1722
palette = 1=#4B5466
palette = 2=#5A5761
palette = 3=#A0081A
palette = 4=#B43644
palette = 5=#976868
palette = 6=#A1769F
palette = 7=#c3c5c7
palette = 8=#5e6773
palette = 9=#4B5466
palette = 10=#5A5761
palette = 11=#A0081A
palette = 12=#B43644
palette = 13=#976868
palette = 14=#A1769F
palette = 15=#c3c5c7
