include-file = ~/.config/polybar/colors.ini

[bar/main]
background = ${colors.background}
foreground = ${colors.foreground}

width = 100%
height = 28
font-0 = JetBrainsMono Nerd Font:size=11
module-margin = 1
enable-ipc = true
modules-left = firefox terminal files corectrl discord steam spotify-click i3 spotify-prev spotify spotify-next spotify-play-pause
modules-center = date
modules-right = pulseaudio memory cpu

[module/firefox]
type = custom/text
content = 

click-left = firefox

[module/terminal]
type = custom/text
content = 

[module/discord]
type = custom/text
content = 󰙯
click-left = discord

[module/corectrl]
type = custom/text
content = 
click-left = corectrl

[module/files]
type = custom/text
content = 

click-left = nautilus

[module/i3]
type = internal/i3
pin-workspaces = true

[module/date]
type = internal/date
interval = 1
date = %Y-%m-%d
time = %H:%M
label = %date% %time%

[module/cpu]
type = internal/cpu
interval = 2
label =   %percentage%%

[module/memory]
type = internal/memory
interval = 2
label =  %percentage_used%%

[module/pulseaudio]
type = internal/pulseaudio
label-volume =   %percentage%%
label-muted = 

[module/spotify-click]
type = custom/text
content = 
click-left = spotify

[module/steam]
type = custom/text
content = 
click-left = steam

[module/spotify]
type = custom/script
tail = true
interval = 1
; prefix symbol is shown before the text
format-prefix = ""
format =
exec = /home/$USER/.config/polybar/scripts/scroll_spotify_status.sh

[module/spotify-prev]
type = custom/script
exec = echo ""
format = 
click-left = playerctl previous -p spotify

[module/spotify-play-pause]
type = custom/ipc
hook-0 = echo ""
hook-1 = echo ""
initial = 1
click-left = playerctl play-pause -p spotify

[module/spotify-next]
type = custom/script
exec = echo "next-song-symbol"
format = 
click-left = playerctl next -p spotify
